#!/usr/bin/env python3
alpha = 10
if alpha > 0: 
	print("The number is positive")
	if alpha < 50:
		print("The number is smaller than 50")
elif alpha < 0:
	print("The number is negative")
else:
	print("The number is zero")
