#!/usr/bin/env python3
alpha = 99
if alpha > 0: 
	print("The number is positive")
	if alpha < 50:
		print("The number is smaller than 50")
		if alpha%2 == 0:
			print("The number is even")
	else: 
		if alpha%3 == 0:
			print("The number is larger than 50 and divisible by 3")
elif alpha < 0:
	print("The number is negative")
else:
	print("The number is zero")
