#!/usr/bin/env python3
import sys
my_name = sys.argv[1]
my_favorite_color = sys.argv[2]
my_favorite_activity = sys.argv[3]
my_favorite_animal = sys.argv[4]
print("My Name is",my_name)
print("My Favorite Color is",my_favorite_color)
print("My Favorite activity is",my_favorite_activity)
print("My favorite animal is",my_favorite_animal)
