#!/usr/bin/env python3
import sys
myrange = range(int(sys.argv[1]), int(sys.argv[2])+1)
#printout = [print(i) for i in myrange if i%2 != 0] #List comprehension method
for i in myrange: #Classic For loop method
	if i%2 != 0: 
		print(i)
