#!/usr/bin/env python3
myrange = range(1,101)
for num in myrange:
	print(num)
#nums = [23,4,6,12,19,33,1,9]
#nums_index = []
#y = 0
#for i in nums:
#	nums_index.append(y)
#	y+=1
#print(f'nums_index: {nums_index}')
#nums_index2 = list(range(len(nums)))
#print(f'nums_index2: {nums_index2}')
