#!/usr/bin/env python3
dna = 'ATGCAGGGGAAACATGATTCAGGAC'
print(f'Original: 5\' {dna} 3\'')
char_to_replace = {'A':'T','T':'A','G':'C','C':'G'}
dna_complement = dna.translate(str.maketrans(char_to_replace))
print(f'Complement: 3\' {dna_complement} 5\'')
#This could also be solved through the following method...
	#Replace A with x
	#Replace T with y
	#Replace G with z
	#Replace C with w
#After these changes, replace to the correct nucleotides...
	#Replace x with T
	#Replace y with A
	#Replace z with C
	#Replace w with G
reverse_complement = dna_complement[::-1]
print(f'Reverse Complement: 5\' {reverse_complement} 3\'')
